#keywords to be added
SEARCH_KEYS = [
    "System Administrator",
    "Network Administrator",
    "IT Support Specialist",
    "Systems Engineer",
    "Windows System Administrator",
    "Linux System Administrator",
    "Azure Administrator",
    "AWS Administrator",
    "Active Directory Administrator",
    "Office 365 Administrator",
    "SQL Server Administrator",
    "Oracle Administrator",
    "Docker Administrator",
    "Kubernetes Administrator",
    "Network Security Administrator",
    "Firewall Administrator",
    "Senior System Administrator",
    "Junior System Administrator",
    "Microsoft Certified System Administrator (MCSA)",
    "Red Hat Certified System Administrator (RHCSA)",
    "AWS Certified SysOps Administrator",
    "CompTIA Network+",
    "CompTIA Security+",
    "Cloud System Administrator",
    "Virtualization Administrator",
    "DevOps Administrator"
]
